export default {
	showHeader:({commit})=>{
              commit('showHeader')
	},
	hideHeader:({commit})=>{
              commit('hideHeader')
	},
	showNav:({commit})=>{
              commit('showNav')
	},
	hideNav:({commit})=>{
              commit('hideNav')
	},
	showLoading:({commit})=>{
             commit('showLoading')
	},
	hideLoading:({commit})=>{
             commit('hideLoading')
	}
}
